modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"

[[mods]]
modId="caster_curios_bonus"
version="1.20.1-1.1.1"
#logoFile="logo.png" #optional
displayName="Caster Curios Bonus"
authors="Rinko1231, FXT1206"
description='''
Add some curios for ISS.
As for Legacy texture, Thanks to some Free assets from ssugmi, Kyrises!
'''
